apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: simple-dc
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deployment-config.name: simple-pod-dc
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deployment-config.name: simple-pod-dc
    spec:
      containers:
      - name: sleep
        image: busybox
        command: ["tail", "-f", "/dev/null"]
  test: false
  triggers:
  - type: ConfigChange
